// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-NHd3Zzw_JttQnJhbXZ5S-1O2QQeIHuE',
    appId: '1:34500432160:web:304658f6eb9ab8f2fb4745',
    messagingSenderId: '34500432160',
    projectId: 'resqtail-0',
    authDomain: 'resqtail-0.firebaseapp.com',
    storageBucket: 'resqtail-0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQ8XNEYn-N6qkXU_3enswZQrpT5UiJlo',
    appId: '1:34500432160:android:817a606c1c075aa5fb4745',
    messagingSenderId: '34500432160',
    projectId: 'resqtail-0',
    storageBucket: 'resqtail-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUl7x8A8XV238ypU2U3A96IrEbXqUhzE',
    appId: '1:34500432160:ios:dc1d9c1e52a52571fb4745',
    messagingSenderId: '34500432160',
    projectId: 'resqtail-0',
    storageBucket: 'resqtail-0.firebasestorage.app',
    iosBundleId: 'com.example.resqtail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUl7x8A8XV238ypU2U3A96IrEbXqUhzE',
    appId: '1:34500432160:ios:dc1d9c1e52a52571fb4745',
    messagingSenderId: '34500432160',
    projectId: 'resqtail-0',
    storageBucket: 'resqtail-0.firebasestorage.app',
    iosBundleId: 'com.example.resqtail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-NHd3Zzw_JttQnJhbXZ5S-1O2QQeIHuE',
    appId: '1:34500432160:web:b1d774750f62eb27fb4745',
    messagingSenderId: '34500432160',
    projectId: 'resqtail-0',
    authDomain: 'resqtail-0.firebaseapp.com',
    storageBucket: 'resqtail-0.firebasestorage.app',
  );
}
