name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          cache: false

      - name: Clean Flutter
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Write .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Write google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          tag=$(git tag --sort=-v:refname | grep '^v' | head -n1 || echo "v1.0.0")
          echo "latest_tag=$tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          v=${{ steps.get_tag.outputs.latest_tag }}
          v=${v#v}
          IFS='.' read -r major minor patch <<< "$v"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Set Flutter version properties
        run: |
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=${{ steps.bump.outputs.new_tag }}" >> android/local.properties

      - name: Accept licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android NDK 27.0.12077973
        run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;27.0.12077973"

      - name: Set NDK environment variable
        run: echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.0.12077973" >> $GITHUB_ENV

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK with version
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/resQtail-${{ steps.bump.outputs.new_tag }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.bump.outputs.new_tag }}
          tag_name: ${{ steps.bump.outputs.new_tag }}
          files: build/app/outputs/flutter-apk/resQtail-${{ steps.bump.outputs.new_tag }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
